{
 "title": "Moon & Sun Rise/Set Copy",
 "time": { "from": "2014-01-02T23:00:00.000Z", "to": "2014-04-05T21:59:59.000Z" },
 "panels": [
  {
   "title": "Time Rise & Set of the Moon & the Sun at Istanbul",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  DateTime AS \"time\",\n  MoonRise_Time AS \"Moon Rise\",\n  MoonSet_Time AS \"Moon Set\",\n  SunRise_Time AS \"Sun Rise\",\n  SunSet_Time AS \"Sun Set\"\nFROM IstanbulSunrise2\nWHERE\n  $__timeFilter(DateTime)\nORDER BY DateTime"
    }
   ]
  },
  {
   "title": "Awake Sun Period",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DateTime AS \"time\",\n  SunSet_Time AS \"Sun Set\",\n  SunRise_Time AS \"Sun Rise\"\nFROM IstanbulSunrise2\nWHERE\n  $__timeFilter(DateTime)\nORDER BY DateTime"
    }
   ]
  },
  {
   "title": "Rise / Set Moon",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DateTime AS \"time\",\n  MoonRise_Time AS \"Moon Rise\",\n  MoonSet_Time AS \"Moon Set\"\nFROM IstanbulSunrise2\nWHERE\n  $__timeFilter(DateTime)\nORDER BY DateTime"
    }
   ]
  }
 ]
}